### ISSUE TITLE
time scale axis

### ISSUE THREAD

**Issue by bsimmo** [ConnectedHumber/AQgraph#1]
is it possible to take the most recent data point for time (which is probably current time anyway, which might be easier)
and fix the axis around that.

I say as prior road (at this point in time) is offline so the graphs don't match up.

**Comment by leftcase** [comment]
I might not get exactly what you mean. If you mean having the current time (i.e. datetime(now) on as the leftmost figure on the 'X' axis, what would we display as we move right along that axis?

**Comment by bsimmo** [comment]
Set (now) as the right most point, end of the axis.

Currently it is set to (last data point for the sensor time).
So they all the graphs are not in sync with each other.

Then trackback a day (or a slider timespan), to the y-axis intercept (aka start point, left most).

**Comment by bsimmo** [comment]
e.g. compare FTW with the one above and below, ftw is one hour behind so they cannot be compared easily as the last data time point is different.  ftw last time should be 7pm (current time*)
Currently 6pm for_ftw_ and 7pm for Exeter Steet / Tranby Ave. 
This also happens if data has not been sent for a few hours, it may be stuck at 2pm e.g. loss of WiFi. It should still end the graph at 7pm .

A quick note, there are two sensors at 8pm the correct time, everyone else seems to be an hour behind ?
 https://github.com/ConnectedHumber/MQTT @BNNorman 
Correct time ones
Sensor CHASN-180325-1 | Templewaters, Kingswood
Sensor CHASN-74F12C-1 | Templewaters, Kingswood

**Comment by BNNorman** [comment]
Those two sensors are mine - they don't send timestamps so the database just contains a storedon datetime (UTC) hence those sensor's reading times are what the server thinks. If you send a timestamp without a timezone the dbLoader assumes it is UTC.

It's an interesting question Ben and quite a headache. 

Mysql doesn't store the timezone offset - it converts the timestamp to UTC - so the dbLoader also converts timestamps to UTC for storing. 

To convert back to a specific time zone requires the mysql command "set time_zone='offset'" prior to retrieving (SELECT) it from the database. SBRL's Api needs to do that so perhaps an issue needs to be raised on the ConnectedHumber/Air-Quality-Web on Github or any code relying on GMT does a timezone conversion before plotting graphs.

Hope that helps.

**Comment by bsimmo** [comment]
Actually is it just a function of the caching as they are all different
this morning.

A fixed scale
```
80* [PM count]
|
|
|
O
   (1 day ago*) ---------- (time.now())[time]
```

* These two change as per needs.
Changing PM count max may be hard, would need to take the max off all
graphs and add a bit.
That makes the comparable for viewing
I think Robin was asking for something similar.


I tried to have a go with a local setup but virtualenv isn't in apt for me
with Python3.
All now, only once setup a Flask/Apachie setup and forgotten what I did.
Ploughed through but got a bit lost doing it to system, going to reverse
everything ;-)

**Comment by leftcase** [comment]
Replaced the automatically generated X-axis ticks with a fixed array of dates calculated from (current date/time - 24 hours) and then incrementing that value by 2 hours for each tick on the axis. Should fix issue with x axis being out of sync for different sensors. You may see slight differences between our sensors and the FTW one.
